# Generated by Django 3.1.3 on 2020-11-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombreArt', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tienda')),
            ],
        ),
    ]
